name: Deploy WebGL

on:
  push:
    # TODO: Remove add-deploy-workflow branch after merging.
    branches: [main, add-deploy-workflow]

jobs:
  build:
    name: Build And Deploy The Game
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-     

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Handle git Commands
      - uses: actions/checkout@v4
      - name: git - Configure Username
        run: git config user.name atb-brown
        shell: bash
      - name: git - Configure Email
        run: git config user.email atb.austin@gmail.com
        shell: bash
      - name: git - Add changes
        run: git --work-tree build/WebGL/WebGL add --all
        shell: bash
      - name: git - Commit changes
        run: git commit -m "Automatic 'Deploy WebGL' action run by .github/workflows/deploy.yml"
        shell: bash
      - name: git - Push changes
        run: git push origin HEAD:deploy --force
        shell: bash

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
